### PR TITLE
Rebuild for python310

### PR DESCRIPTION
**Pull request by Czaki**
…nda-forge-pinning 2022.04.01.12.21.46
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Czaki** [comment]
@jaimergp I create a copy of #1 to work on the most recent version but do not understand why the build fails. Could you check?

**Comment by goanpeca** [comment]
`package imagecodecs-2021.11.20-py310h16c5d60_2 requires cfitsio >=4.0.0,<4.0.1.0a0, but none of the providers can be installed`

**Comment by Czaki** [comment]
But there is `cfitsio`  package on conda with such a version https://anaconda.org/conda-forge/cfitsio/files ?
And the error for Linux is different.

**Comment by jaimergp** [comment]
The offending package might be a different one than the reported (a 2nd-order dependency of that one, for example). What I usually do is to try to install the reported one, which usually brings up the _next_ one, until I find the one missing.

This works locally:

```
CONDA_SUBDIR=osx-64 mamba create -n test python=3.10 imagecodecs=2021.11.20=py310h16c5d60_2 --dry-run
```

```
CONDA_SUBDIR=linux-64 mamba create -n test python=3.10 requests=2.23.0=pyh8c360ce_2 --dry-run
```

But the full env (for example, the one taken from the Linux logs):

```
 - pip
 - openpyxl >=2.4.9
 - qtawesome >=1.0.3
 - tifffile >=2020.9.30
 - simpleitk >=1.1.0
 - napari >=0.4.8
 - appdirs >=1.4.4
 - magicgui >=0.3.3
 - scipy >=1.2.0
 - python >=3.10,<3.11.0a0
 - sympy >=1.1.1
 - nme >=0.1.4
 - qtpy >=1.7.0
 - xlsxwriter
 - imagecodecs >=2020.5.30
 - xlrd >=1.1.0
 - sentry-sdk >=0.14.3
 - oiffile >=2019.1.1
 - packaging >=20.0
 - requests >=2.18.0
 - numpy >=1.18.0
 - psygnal >=0.2.0
 - vispy >=0.6.4
 - czifile >=2019.5.22
 - partsegdata 0.10.0.*
 - partsegcore-compiled-backend >=0.13.11
 - h5py >=2.8.0
 - imageio >=2.5.0
 - traceback-with-variables >=2.0.4
 - defusedxml >=0.6.0
 - superqt >=0.2.4
 - pandas >=0.24.0
 - mahotas >=1.4.9
 - six >=1.11.0
 - python_abi 3.10.* *_cp310
```

does reproduce the problem.

My approach from now on would be to paste this in a `environment.yml` and then run `CONDA_SUBDIR=linux-64 mamba env create -f environment.yml --dry-run` removing one package per attempt, until it runs again. That would be the culprit.

**Comment by Czaki** [comment]
@jaimergp @goanpeca  I just found that the problematic package is h5py. But Still I do not found where there is conflict between h5py and imagecodecs and why it is not present on py39.

**Comment by jaimergp** [comment]
I guess there's a package missing for Python 3.10 in that dependency chain. The migration was closed recently, and the data can be found [here](https://conda-forge.org/status/#python310). There are some feedstocks who didn't merge their PR yet, and some of them never got the PR due to other issues. Maybe one of them is the culprit?

**Comment by jaimergp** [comment]
The error on macOS mentions libitk and hdf5, though. And libitk [has a pending PR](https://github.com/conda-forge/libitk-feedstock/pull/70) for a hdf5 migration... Maybe that's the issue?

**Comment by Czaki** [comment]
libitk has merged PR https://github.com/conda-forge/libitk-feedstock/pull/72 and still build fails :(

**Comment by goanpeca** [comment]
Seems to be working now @Czaki !

**Comment by Czaki** [comment]
Thanks for your patience and support.

**Comment by jaimergp** [comment]
I am curious; what was the fix?

**Comment by Czaki** [comment]
I think that some of the packages that make conflict have a new release.

**Pull request merged**
